namespace: pedrobagatin
name: hello_world
version: 1.0.2
readme: README.md
authors:
- Pedro Bagatin <pedrobagatin@yahoo.com.br>
description: Minha primeira collection Ansible
license: MIT
repository: https://github.com/pedrobagatin/hello_world